apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default-gcp
spec:
  projectID: anthos-crossplane
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-creds
      key: creds